name: Android CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
          restore-keys: |
            ${{runner.os}}-gradle-  

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create LOCAL_PROPERTIES
        run: |
          echo -e '${{ secrets.BASE_URL }}' > ./local.properties

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew build
